### ISSUE TITLE
任务申请

### ISSUE THREAD

**Issue by vsxen** [Microndgt/The-Flask-Mega-Tutorial#2]
感觉先在issue认领，再发PR，可能会避免重复劳动

另外可以另起一个code  branch  ，根据part打tag

章节 | 预计完成时间 | 翻译者
------- | -------|-------
part4 | 2018年01月15日| @vsxen

示例
```
章节 | 预计完成时间 | 翻译者
------- | -------|-------
part | 2018年01月15日| 
```

**Comment by Microndgt** [comment]
我目前是这么做的，如果我要翻译新的章节，我会初始化翻译文件，然后很快做一个初始提交，发一个pr，这样以后的提交都在这个pr，直到完成被合并。别人也可以及时的在pr看到相应哪些文章已经被翻译了。

**Comment by vsxen** [comment]
那样也可以 不过自我感觉没有issue 方便些（可能错觉吧）。 还有code branch？ 要做吗？

**Comment by Microndgt** [comment]
我觉得master就够了吧？只要通过review的pr合并到master上，大家看到的就是最新以及当前最优的。我现在就开了part3的pr，你可以看下，然后有什么问题我们都可以在pr上提。你也可以开始一个part4的pr

**Comment by Microndgt** [comment]
当然如果有人在issue提了问题，那么可以指定某个翻译者或者自己来修复这个问题。如果有人想翻译还得翻一遍issue，我觉得可能稍微麻烦一点。不论怎样，最后不论哪种方式你总是要在PR中看到现在正在做什么。
