### ISSUE TITLE
关于代码高亮和中文与英文的问题

### ISSUE THREAD

**Issue by sixcold** [Microndgt/The-Flask-Mega-Tutorial#4]
- 是否添加代码高亮的设置？类似
```python
import time
print('hello,world')
````
- 中文和英文单词之间是不是加空格？类似
```
中文Chinese英文English
或者
中文 Chinese 英文 English
```

可能我是强迫症 :)

**Comment by Microndgt** [comment]
好的，谢谢指出。

**Comment by vsxen** [comment]
这里算是有规范 https://github.com/sparanoid/chinese-copywriting-guidelines

**Comment by Microndgt** [comment]
@vsxen 赞

**Comment by Microndgt** [comment]
我写了个小工具：https://github.com/Microndgt/The-Flask-Mega-Tutorial#issue4-文档格式检查工具
用于检测文章中有哪些部分需要进行格式化的
